baseurl: ""
url: "http://flexible.gs"

markdown: kramdown

gems:
  - jekyll-multiple-languages
  - jekyll-sitemap

languages:
  - en
  - tr

language_default: 'en'

fill_default_content: true

t:
  en:
    homepage:
      title: "Homepage"
    install:
      title: "Install"
    learn:
      title: "Learn"
    support:
      title: "Support"
    motivation:
      title: "Motivation"
    future:
      title: "Future"
  tr:
    homepage:
      title: "Anasayfa"
    install:
      title: "Kurulum"
    learn:
      title: "Öğrenme"
    support:
      title: "Destek"
    motivation:
      title: "Motivasyon"
    future:
      title: "Gelecek"

sitemap: true
